spring:
  application:
    name: COMMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/postdb
    username: root
    password: Busy100%

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect






